version: "2"

run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - revive
    - misspell
    - nilerr
    - bodyclose
    - errname
    - errorlint

  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
    revive:
      rules:
        - name: blank-imports
        - name: exported
        - name: unreachable-code
        - name: unexported-return
    errcheck:
      check-type-assertions: true
    errorlint:
      errorf: true
      asserts: true
      comparison: true
